### PR TITLE
img input component

### PR DESCRIPTION
**Pull request by nisargpawade**
- added img component
  - round img
  - responsive img
- added input component
  - normal input
  - input with validation & error style

image

image

### CODE REVIEW

**Review by vijaytembugade — APPROVED** [review]
Great work brother,

**Comment by nisargpawade** [comment]
> Great work brother,

thank you for your kind words birthday boy

**Review by abhijeetekad — APPROVED** [review]

**Review by vaibhav18matere — APPROVED** [review]
looks good to me 
just change the e-mail input outline color

**Comment by nisargpawade** [comment]
> looks good to me just change the e-mail input outline color

is it light or dark

**Pull request merged**
